name: Health Check

on: push

jobs:
  health_check:
    runs-on: ubuntu-latest 
    steps:
    - name: Check Application Health
      uses: fjogeleit/http-request-action@v1.8.0
      with:
        url: "https://weeti-pokemon-dx.fly.dev/.ping"
        method: "GET"