name: Lint Workflow

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
    - name: Check Out Repository
      uses: actions/checkout@v3

    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Dependencies
      run: npm install  

    - name: Run Linter
      run: npm run eslint

    - name: Run Project
      run: npm run build

    - name: Run Tests
      run: npm test

    - name: e2e Tests
      uses: cypress-io/github-action@v5
      with:
        command: npm run test:e2e
        start: npm run start-prod
        wait-on: http://localhost:5000

    - name: Deploy to Production
      if: >
        github.event_name == 'push' &&
        github.ref == 'refs/heads/master' &&
        !contains(join(github.event.commits, '\n'), '#skip')
      run: echo "npm run start-prod"

    - name: Bump version and push tag
      if: >
        github.event_name == 'push' &&
        github.ref == 'refs/heads/master' &&
        !contains(join(github.event.commits.*.message, '\n'), '#skip')
      
      uses: anothrNick/github-tag-action@1.64.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: "true"
        DEFAULT_BUMP: patch
        DRY_RUN: "false"

  notify_failure:
    runs-on: ubuntu-20.04
    needs: build_and_test
    if: failure()
    steps:
      - name: Failure Notification
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          message: "Build or deployment failed! Check GitHub Actions for more details."